<template><div class="ky-page" v-loading="loading"><div class="ky-page-header"><h2 class="ky-page-title">健康知识库</h2><el-space><el-button :loading="reindexing" @click="reindex">重建向量索引</el-button><el-button type="primary" @click="edit()">新增条目</el-button></el-space></div><div class="ky-card"><el-space wrap><el-input v-model="keyword" placeholder="搜索标题 / 正文" clearable @keyup.enter="page=1;load()" /><el-button @click="page=1;load()">搜索</el-button></el-space><el-table :data="rows" style="margin-top:16px"><el-table-column prop="title" label="标题" min-width="200" /><el-table-column prop="category" label="分类" /><el-table-column label="状态"><template #default="{row}">{{ row.enabled?'启用':'停用' }}</template></el-table-column><el-table-column prop="updated_at" label="更新时间" min-width="160" /><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev,pager,next,total" @current-change="load" /><el-alert v-if="error" type="error" :closable="false" :title="error" /></div><el-dialog v-model="dialog" :title="form.document_id || form.knowledge_id || form.doc_id ? '编辑知识条目':'新增知识条目'" width="min(760px,95vw)"><el-form label-position="top"><el-form-item label="标题"><el-input v-model="form.title" maxlength="200" /></el-form-item><el-form-item label="分类"><el-select v-model="form.category" filterable allow-create default-first-option style="width:100%"><el-option v-for="category in categories" :key="category" :label="category" :value="category" /></el-select></el-form-item><el-form-item label="正文（附真实来源说明）"><el-input v-model="form.content" type="textarea" :rows="10" /></el-form-item><el-form-item label="启用检索"><el-switch v-model="form.enabled" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存条目</el-button></template></el-dialog></div></template>
<script setup>
import {ref,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {listKnowledge,addKnowledge,saveKnowledge,deleteKnowledge,reindexKnowledge} from '@/api'
import {asList} from '@/utils/format'
const rows=ref([]),form=ref({}),keyword=ref(''),page=ref(1),total=ref(0),dialog=ref(false),loading=ref(false),saving=ref(false),reindexing=ref(false),error=ref('')
const categories=['高血压','糖尿病','心率异常','睡眠','老年运动','老年饮食','常见问题','安全提示']
const idOf=r=>r.document_id||r.knowledge_id||r.doc_id||r.id
async function load(){loading.value=true;error.value='';try{const d=await listKnowledge({page:page.value,page_size:20,keyword:keyword.value||undefined});rows.value=asList(d);total.value=d.total??rows.value.length}catch(e){error.value=e.message}finally{loading.value=false}}
function edit(row){form.value=row?{...row}:{title:'',category:'常见问题',content:'',enabled:true};dialog.value=true}
async function save(){if(!form.value.title.trim()||!form.value.content.trim())return ElMessage.warning('标题和正文不能为空');saving.value=true;try{const p={title:form.value.title,category:form.value.category,content:form.value.content,enabled:form.value.enabled},id=idOf(form.value);if(id)await saveKnowledge(id,p);else await addKnowledge(p);dialog.value=false;await load();ElMessage.success('知识条目已保存')}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function remove(row){try{await ElMessageBox.confirm('确认删除知识条目 '+row.title+'？删除后退出有效检索。','删除知识',{type:'warning'});await deleteKnowledge(idOf(row));await load();ElMessage.success('条目已删除')}catch(e){if(!['cancel','close'].includes(e))ElMessage.error(e.message)}}
async function reindex(){reindexing.value=true;try{const d=await reindexKnowledge();ElMessage.success(d?.message||'索引重建完成')}catch(e){ElMessage.error(e.message)}finally{reindexing.value=false}}
onMounted(load)
</script>
