<template><div class="ky-page" v-loading="loading"><div class="ky-page-header"><h2 class="ky-page-title">用户管理</h2><el-button type="primary" @click="dialog=true">创建护工 / 管理员账号</el-button></div><div class="ky-card"><el-space wrap><el-input v-model="keyword" placeholder="姓名 / 手机号" clearable @keyup.enter="page=1;load()" /><el-select v-model="role" clearable placeholder="全部角色" @change="page=1;load()"><el-option v-for="(label,value) in roles" :key="value" :label="label" :value="value" /></el-select><el-button @click="page=1;load()">查询</el-button></el-space><el-table :data="rows" style="margin-top:16px"><el-table-column prop="name" label="姓名" /><el-table-column prop="phone" label="手机号" min-width="140" /><el-table-column label="角色"><template #default="{row}">{{ roles[row.role] }}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.enabled ? 'success':'danger'">{{ row.enabled?'启用':'禁用' }}</el-tag></template></el-table-column><el-table-column label="操作" min-width="220"><template #default="{row}"><el-button link :type="row.enabled?'danger':'success'" :disabled="row.user_id===me.user_id" @click="toggle(row)">{{ row.enabled?'禁用':'启用' }}</el-button><el-button v-if="['CARE','ADMIN'].includes(row.role)" link type="primary" :disabled="row.user_id===me.user_id" @click="changeRole(row)">改为{{ row.role==='CARE'?'管理员':'护工' }}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev,pager,next,total" @current-change="load" /><el-alert v-if="error" type="error" :closable="false" :title="error" /></div><el-dialog v-model="dialog" title="创建机构账号" width="min(520px,95vw)"><el-form label-position="top"><el-form-item label="角色"><el-select v-model="form.role"><el-option label="护工" value="CARE" /><el-option label="管理员" value="ADMIN" /></el-select></el-form-item><el-form-item label="姓名"><el-input v-model="form.name" maxlength="30" /></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone" maxlength="11" /></el-form-item><el-form-item label="初始密码"><el-input v-model="form.password" type="password" show-password /></el-form-item><p class="ky-sub">仅创建护工和管理员。老人、家属通过公开注册页面建号。</p></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建账号</el-button></template></el-dialog></div></template>
<script setup>
import {ref,reactive,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {listUsers,createUser,setUserEnabled,setUserRole} from '@/api'
import {asList} from '@/utils/format'
import {getUser} from '@/utils/auth'
const me=getUser(),rows=ref([]),page=ref(1),total=ref(0),keyword=ref(''),role=ref(''),loading=ref(false),error=ref(''),dialog=ref(false),saving=ref(false)
const roles={ELDER:'老人',FAMILY:'家属',CARE:'护工',ADMIN:'管理员'},form=reactive({name:'',phone:'',password:'',role:'CARE'})
async function load(){loading.value=true;error.value='';try{const d=await listUsers({page:page.value,page_size:20,keyword:keyword.value||undefined,role:role.value||undefined});rows.value=asList(d);total.value=d.total??rows.value.length}catch(e){error.value=e.message}finally{loading.value=false}}
async function create(){if(!form.name.trim()||!/^1\d{10}$/.test(form.phone)||!form.password)return ElMessage.warning('请填写姓名、正确手机号和密码');saving.value=true;try{await createUser({...form});dialog.value=false;form.name='';form.phone='';form.password='';await load();ElMessage.success('账号已创建')}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function toggle(row){try{await ElMessageBox.confirm('确认'+(row.enabled?'禁用':'启用')+'账号 '+row.name+'？','修改账号状态',{type:'warning'});await setUserEnabled(row.user_id,!row.enabled);await load()}catch(e){if(!['cancel','close'].includes(e))ElMessage.error(e.message)}}
async function changeRole(row){try{const role=row.role==='CARE'?'ADMIN':'CARE';await ElMessageBox.confirm('确认将 '+row.name+' 改为'+roles[role]+'？旧登录会话会失效。','修改角色',{type:'warning'});await setUserRole(row.user_id,role);await load()}catch(e){if(!['cancel','close'].includes(e))ElMessage.error(e.message)}}
onMounted(load)
</script>
