<template><div class="ky-page" v-loading="loading"><div class="ky-page-header"><h2 class="ky-page-title">{{ data.profile?.name || '老人' }} 的照护详情</h2><el-button @click="$router.push('/care/profile/edit?id='+id)">编辑档案</el-button><el-button @click="$router.push('/care/profile/edit?source_profile_id='+id)">新建负责档案</el-button><el-button type="primary" @click="$router.push('/care/input?profile_id='+id)">代录健康指标</el-button></div><el-alert v-if="error" type="error" :closable="false" :title="error" /><template v-if="data.profile"><div class="ky-card"><el-descriptions :column="2" border><el-descriptions-item label="年龄">{{ data.profile.age ?? '—' }}</el-descriptions-item><el-descriptions-item label="过敏史">{{ data.profile.allergy || '未记录' }}</el-descriptions-item><el-descriptions-item label="病史">{{ data.profile.medical_history || '未记录' }}</el-descriptions-item><el-descriptions-item label="紧急联系人">{{ data.profile.emergency_contact }} {{ data.profile.emergency_phone }}</el-descriptions-item></el-descriptions></div><div class="ky-card"><div class="ky-card__title">最近指标</div><el-table :data="latestRows"><el-table-column label="类型"><template #default="{row}">{{ NAME[row.type] }}</template></el-table-column><el-table-column label="值"><template #default="{row}">{{ recordText(row) }}</template></el-table-column><el-table-column prop="measured_at" label="测量时间" /><el-table-column label="异常"><template #default="{row}"><StatusTag kind="abnormal" :value="row.is_abnormal" /></template></el-table-column></el-table></div><div class="ky-card"><div class="ky-card__title">相关预警</div><el-table :data="data.alerts || data.open_alerts || []" @row-click="row=>$router.push('/care/alert/'+row.warning_id)"><el-table-column prop="value_text" label="指标值" /><el-table-column label="状态"><template #default="{row}"><StatusTag :value="row.status" /></template></el-table-column><el-table-column prop="created_at" label="触发时间" /><el-table-column label="查看"><template #default>查看详情与处理 →</template></el-table-column></el-table></div></template></div></template>
<script setup>
import { ref,computed,onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { getCareElder } from '@/api'
import { NAME,recordText } from '@/utils/format'
import StatusTag from '@/components/common/StatusTag.vue'
const id=useRoute().params.id,data=ref({}),loading=ref(false),error=ref('')
const latestRows=computed(()=>data.value.latest_records || (Array.isArray(data.value.latest)?data.value.latest:Object.values(data.value.latest||data.value.latest_indicators||{}).filter(Boolean)))
onMounted(async()=>{loading.value=true;try{data.value=await getCareElder(id)}catch(e){error.value=e.message}finally{loading.value=false}})
</script>
