# -*- coding: utf-8 -*-
"""03.概要设计 v2.0 生成器 · 模块元数据
单一来源：模块划分、功能定义、类图元素、模块结构图元素。
改这里 → 重跑 build_md.py / figures.py 即可全文重建。
"""

# 三个功能域，用于系统结构图归组
DOMAINS = [
    ("用户与关系域", ["M1", "M2", "M6", "M7"]),
    ("健康与预警域", ["M3", "M5"]),
    ("智能与配置域", ["M4", "M8", "M9"]),
]


def slug(text):
    """文件名安全化：去掉空格与路径分隔符"""
    return text.replace(" ", "").replace("/", "-").replace("·", "-")

# 九个后端模块
MODULES = [
    {
        "code": "M1",
        "cn": "认证与权限",
        "en": "AUTH",
        "duty": "注册（角色白名单）、登录、登出、当前用户、JWT 签发与校验、越权拦截",
        "chapter": "契约第 2 章",
        "tables": ["user"],
        "frs": ["FR-AUTH-001", "FR-AUTH-002", "FR-AUTH-003", "FR-AUTH-004",
                "FR-AUTH-005", "FR-AUTH-007", "FR-AUTH-008", "FR-AUTH-012"],
        "features": [
            ("注册", "手机号 + 密码 + 姓名注册；角色白名单仅 ELDER / FAMILY，传入 CARE / ADMIN 返回 4003（D-01）", "FR-AUTH-001"),
            ("登录", "手机号 + 密码登录，校验通过后签发 JWT 并记录最近登录时间", "FR-AUTH-002"),
            ("JWT 鉴权与会话保持", "登录后签发 token，过期或失效返回 1001，前端跳登录页", "FR-AUTH-003 / 008"),
            ("角色授权与越权拦截", "ELDER / FAMILY / CARE / ADMIN 四角色权限区分；跨角色越权访问返回 1002", "FR-AUTH-004 / 005"),
            ("登出", "主动退出，服务端将 token 加入失效列表", "FR-AUTH-007"),
            ("密码与会话安全", "密码 bcrypt 加密存储、禁明文、不回显；登录失败限次防暴力破解", "FR-AUTH-012"),
        ],
        "classes": [
            ("AuthRouter", "接口层：注册 / 登录 / 登出 / 当前用户 4 个端点", "#eff6ff", "#3b82f6"),
            ("AuthService", "应用层：注册白名单校验、密码比对、登录编排", "#eff6ff", "#3b82f6"),
            ("JwtProvider", "签发与解析 JWT，维护 token 失效列表", "#f0fdf4", "#16a34a"),
            ("UserRepository", "数据层：按手机号查用户、写登录时间", "#f8fafc", "#64748b"),
            ("UserModel", "实体：user 表映射（四类角色 + 状态）", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("AuthRouter", "AuthService", "调用"),
            ("AuthService", "JwtProvider", "签发"),
            ("AuthService", "UserRepository", "查询"),
            ("UserRepository", "UserModel", "映射"),
        ],
        "structure": {
            "iface": ["AuthRouter\\napp/api/v1/auth.py"],
            "service": ["AuthService\\n注册白名单 · 密码校验 · 登录编排"],
            "data": ["UserRepository\\nuser 表读写"],
            "side": ["Depends(get_current_user)\\n横切：统一鉴权与出入参校验",
                     "bcrypt 密码哈希",
                     "sys_config\\n登录失败限次"],
        },
    },
    {
        "code": "M2",
        "cn": "健康档案",
        "en": "PROFILE",
        "duty": "档案增删改查、软删除、按角色的数据隔离",
        "chapter": "契约第 3 章",
        "tables": ["elder_profile"],
        "frs": ["FR-HEALTH-001", "FR-HEALTH-002", "FR-HEALTH-003", "FR-HEALTH-004", "FR-HEALTH-014"],
        "features": [
            ("档案创建", "一位账号可建 1~N 份档案（本人 / 代管老人），录入基本信息、病史、慢病标签", "FR-HEALTH-001"),
            ("档案查看", "返回基本信息、既往病史、过敏史、慢病标签", "FR-HEALTH-002"),
            ("数据隔离", "老人返回本人、家属返回已绑定、护工返回负责、管理员返回全部；隔离在后端强制实现", "FR-FAMILY-011"),
            ("档案修改", "基本资料与慢病标签增删改", "FR-HEALTH-003"),
            ("档案删除", "二次确认后软删除（deleted 标记），保留历史数据可追溯", "FR-HEALTH-004"),
            ("多档案归属", "同一账号可归属多份档案，供家属/护工快速切换", "FR-HEALTH-014"),
        ],
        "classes": [
            ("ProfileRouter", "接口层：档案列表 / 新增 / 详情 / 更新 / 删除", "#eff6ff", "#3b82f6"),
            ("ProfileService", "应用层：按角色计算可见档案范围", "#eff6ff", "#3b82f6"),
            ("ScopeResolver", "解析当前用户的档案可见集合（本人 / 绑定 / 负责 / 全部）", "#fef3c7", "#d97706"),
            ("ProfileRepository", "数据层：档案读写与软删除过滤", "#f8fafc", "#64748b"),
            ("ElderProfileModel", "实体：elder_profile 表映射", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("ProfileRouter", "ProfileService", "调用"),
            ("ProfileService", "ScopeResolver", "取范围"),
            ("ProfileService", "ProfileRepository", "读写"),
            ("ProfileRepository", "ElderProfileModel", "映射"),
        ],
        "structure": {
            "iface": ["ProfileRouter\\napp/api/v1/profiles.py", "ProfileIn / ProfileUpdate\\nPydantic 校验"],
            "service": ["ProfileService\\n范围计算 · 软删除语义"],
            "data": ["ProfileRepository\\nelder_profile 读写"],
            "side": ["family_bind\\n家属可见范围", "care_relation\\n护工负责范围"],
        },
    },
    {
        "code": "M3",
        "cn": "健康指标",
        "en": "HEALTH",
        "duty": "指标录入（五类）、列表、删除、趋势数据、异常同步检测",
        "chapter": "契约第 4 章",
        "tables": ["health_record"],
        "frs": ["FR-HEALTH-005", "FR-HEALTH-010", "FR-HEALTH-011", "FR-HEALTH-012",
                "FR-HEALTH-013", "FR-ALERT-001"],
        "features": [
            ("指标录入", "血压 / 血糖 / 心率 / 睡眠 / 步数 五类，录入前做范围与类型校验", "FR-HEALTH-005~009"),
            ("统一指标存储", "统一表 + type 字段区分指标类型，避免五张表结构重复（DB-2）", "FR-HEALTH-010"),
            ("指标历史列表", "按档案 + 类型分页查询，按测量时间倒序", "FR-HEALTH-011"),
            ("异常同步检测", "录入成功后同步执行阈值检测，命中即返回 risk_level 与 warning_id", "FR-ALERT-001"),
            ("趋势数据", "输出 ECharts 可直接渲染的 dates / series 结构，正常范围来自 sys_config", "FR-HEALTH-012"),
            ("异常点标注", "趋势数据附带 abnormal_points，供前端高亮超阈值点", "FR-HEALTH-013"),
        ],
        "classes": [
            ("HealthRouter", "接口层：录入 / 列表 / 删除 / 趋势", "#eff6ff", "#3b82f6"),
            ("HealthRecordService", "应用层：录入校验、趋势聚合", "#eff6ff", "#3b82f6"),
            ("ThresholdChecker", "按 sys_config 阈值判定异常与风险等级", "#fef3c7", "#d97706"),
            ("HealthRecordRepository", "数据层：指标写入与趋势查询", "#f8fafc", "#64748b"),
            ("HealthRecordModel", "实体：health_record 表映射（val1 / val2）", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("HealthRouter", "HealthRecordService", "调用"),
            ("HealthRecordService", "ThresholdChecker", "判级"),
            ("HealthRecordService", "HealthRecordRepository", "读写"),
            ("HealthRecordRepository", "HealthRecordModel", "映射"),
        ],
        "structure": {
            "iface": ["HealthRouter\\napp/api/v1/health.py", "五类指标入参模型"],
            "service": ["HealthRecordService\\n录入校验 · 趋势聚合", "ThresholdChecker\\n阈值判定（读 sys_config）"],
            "data": ["HealthRecordRepository\\nhealth_record 读写"],
            "side": ["sys_config\\n阈值不硬编码（铁律 2）", "→ 触发 M5 预警生成"],
        },
    },
    {
        "code": "M4",
        "cn": "AI 健康咨询与智能体编排",
        "en": "AI · Agent",
        "duty": "意图识别路由、四类 Agent 编排、RAG 检索增强、安全分级与降级、会话历史",
        "chapter": "契约第 5 章",
        "tables": ["chat_session", "chat_message", "knowledge_document", "knowledge_chunk", "ai_log"],
        "frs": ["FR-AI-001", "FR-AI-002", "FR-AI-003", "FR-AI-004", "FR-AI-005",
                "FR-AI-006", "FR-AI-007", "FR-AI-008", "FR-AI-009", "FR-AI-010",
                "FR-AI-011", "FR-AI-014", "FR-AI-015", "FR-KB-003"],
        "features": [
            ("发起咨询", "选择档案 + 输入问题（或点预设问题按钮），session_id 为空时自动建会话", "FR-AI-001"),
            ("意图识别路由", "四类意图 NORMAL / DATA / ABNORMAL / EMERGENCY，由 IntentRouter 判定", "FR-AI-003"),
            ("多 Agent 编排", "HealthAgent 普通咨询 / HealthDataAgent 数据类 / RiskAgent 异常 / EmergencyAgent 紧急", "FR-AI-004~007"),
            ("RAG 检索增强", "问题向量化 → 向量库 Top-K 召回 → 注入 Prompt，回答附 sources 来源", "FR-AI-008 / KB-003"),
            ("档案个性化", "组装档案摘要（慢病标签、过敏史）+ 近 7 天指标一起送入模型", "FR-AI-002"),
            ("Risk Agent 联动预警", "异常意图判定风险等级并生成预警，返回 warning_id", "FR-AI-006"),
            ("回答适老化与免责", "长文分段、要点化输出；每次响应固定返回免责声明", "FR-AI-009 / 011"),
            ("安全分级与降级", "L1~L4 安全分级 + 敏感词兜底；模型不可用返回 3001 但业务主流程仍可运行（D-04）", "FR-AI-014"),
            ("限流与费用控制", "单次限字数、按用户控制调用频率，超出返回 3002", "FR-AI-015"),
            ("历史咨询记录", "按档案查看会话与消息列表，可删除会话", "FR-AI-010"),
        ],
        "classes": [
            ("ChatRouter", "接口层：发起咨询 / 会话列表 / 消息 / 删除会话", "#f5f3ff", "#8b5cf6"),
            ("ChatService", "应用层：会话落库、档案摘要组装、调用编排器", "#f5f3ff", "#8b5cf6"),
            ("IntentRouter", "意图识别：NORMAL / DATA / ABNORMAL / EMERGENCY", "#fef3c7", "#d97706"),
            ("AgentOrchestrator", "按意图选择并执行 Agent，汇总回答与来源", "#f5f3ff", "#8b5cf6"),
            ("BaseAgent", "Agent 抽象：统一 prompt 组装、模型调用、安全分级、降级", "#f0fdf4", "#16a34a"),
            ("KnowledgeRetriever", "RAG：问题向量化 + Top-K 召回 + 来源标注", "#f0fdf4", "#16a34a"),
            ("LlmClient", "模型网关：换模型只改 .env 的 LLM_PROVIDER", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("ChatRouter", "ChatService", "调用"),
            ("ChatService", "IntentRouter", "识别意图"),
            ("ChatService", "AgentOrchestrator", "执行"),
            ("BaseAgent", "HealthAgent", "泛化"),
            ("BaseAgent", "HealthDataAgent", "泛化"),
            ("BaseAgent", "RiskAgent", "泛化"),
            ("BaseAgent", "EmergencyAgent", "泛化"),
            ("BaseAgent", "KnowledgeRetriever", "检索"),
            ("BaseAgent", "LlmClient", "调用模型"),
        ],
        "agents": [
            ("HealthAgent", "普通咨询：RAG 检索 + 个性化健康建议"),
            ("HealthDataAgent", "数据类：查库 + 趋势分析 + 回答"),
            ("RiskAgent", "异常：风险分级 + 生成预警 + 通知"),
            ("EmergencyAgent", "紧急：立即建议求助 + 通知紧急联系人"),
        ],
        "structure": {
            "iface": ["ChatRouter\\napp/api/v1/ai.py", "ChatIn / MessageOut\\n会话与消息模型"],
            "service": ["ChatService\\n会话落库 · 档案摘要组装", "AgentOrchestrator\\nIntentRouter → Agent"],
            "data": ["ChatRepository\\nchat_session / chat_message", "VectorStore\\nknowledge_chunk / Chroma·FAISS"],
            "side": ["LlmClient\\n.env 的 LLM_PROVIDER\\n换模型不改代码", "ai_log\\n调用耗时与失败留痕", "失败降级：返回 3001\\n主流程不阻塞（D-04）"],
        },
    },
    {
        "code": "M5",
        "cn": "主动预警",
        "en": "ALERT",
        "duty": "阈值规则引擎、风险四级判定、AI 摘要异步生成、站内通知分发、处理闭环与已读状态",
        "chapter": "契约第 6 章",
        "tables": ["health_warning", "alert_receiver", "warning_handle_record"],
        "frs": ["FR-ALERT-002", "FR-ALERT-003", "FR-ALERT-004", "FR-ALERT-005",
                "FR-ALERT-006", "FR-ALERT-007", "FR-ALERT-008", "FR-ALERT-009",
                "FR-ALERT-010", "FR-ALERT-011", "FR-ALERT-012"],
        "features": [
            ("阈值规则引擎", "阈值全部来自 sys_config，改阈值即时生效，代码不写死（铁律 2）", "FR-ALERT-002 / ADMIN-009"),
            ("风险四级判定", "0 正常 / 1 轻度 / 2 较高 / 3 高风险，参考档案慢病标签做个体微调", "FR-ALERT-003"),
            ("AI 摘要异步生成", "预警先生成后异步补摘要；summary_status 覆盖 PENDING / SUCCESS / FAILED / SKIPPED", "FR-ALERT-004"),
            ("站内通知分发", "按接收人写入 alert_receiver；老人端、家属端、护工端按角色可见（D-03）", "FR-ALERT-005~007"),
            ("紧急升级", "L3 高风险标记后不等待 AI 摘要立即通知，保证时效（D-04）", "FR-ALERT-008"),
            ("处理闭环", "处理状态 PENDING → PROCESSING → RESOLVED / IGNORED，与已读状态相互独立（D-05）", "FR-ALERT-009"),
            ("处理留痕", "登记处理方式（已联系 / 安排上门 / 送医 / 继续观察）与说明，写入留痕表", "FR-ALERT-010"),
            ("已读状态与未读数", "点开详情只更新本人那条接收记录；未读数为当前用户口径", "FR-ALERT-011"),
            ("预警详情", "展示指标值、阈值、近 7 天历史趋势与全部处理记录", "FR-ALERT-012"),
            ("摘要重试", "摘要失败可由用户或管理员手动重试，AI 不可用不影响预警本身", "FR-ALERT-004"),
        ],
        "classes": [
            ("AlertRouter", "接口层：列表 / 详情 / 处理 / 状态 / 已读 / 重试 / 统计 / 未读数", "#fef2f2", "#ef4444"),
            ("AlertService", "应用层：预警查询、处理闭环、统计口径", "#fef2f2", "#ef4444"),
            ("ThresholdRuleEngine", "读 sys_config 阈值判定等级，产出预警实体", "#fef3c7", "#d97706"),
            ("AlertNotifyService", "按接收人范围写入 alert_receiver 并分发站内通知", "#f0fdf4", "#16a34a"),
            ("SummaryWorker", "异步生成 AI 摘要，失败可重试（不阻塞主流程）", "#f0fdf4", "#16a34a"),
            ("AlertRepository", "数据层：预警 / 接收人 / 留痕三表读写", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("AlertRouter", "AlertService", "调用"),
            ("AlertService", "ThresholdRuleEngine", "判级"),
            ("ThresholdRuleEngine", "AlertNotifyService", "生成后分发"),
            ("AlertService", "SummaryWorker", "异步摘要"),
            ("AlertService", "AlertRepository", "读写"),
        ],
        "structure": {
            "iface": ["AlertRouter\\napp/api/v1/alerts.py", "NotificationsRouter\\n未读数"],
            "service": ["AlertService\\n处理闭环 · 统计", "ThresholdRuleEngine\\n读 sys_config", "SummaryWorker\\n异步摘要 · 可重试"],
            "data": ["health_warning 预警", "alert_receiver 接收人已读", "warning_handle_record 留痕"],
            "side": ["M3 录入触发（同步）", "M4 RiskAgent 触发", "站内通知（D-03）\\n无短信 / 电话"],
        },
    },
    {
        "code": "M6",
        "cn": "家属绑定",
        "en": "FAMILY",
        "duty": "申请 → 确认 → 生效三段式、待确认列表、确认/拒绝、解绑、代管老人列表",
        "chapter": "契约第 7 章",
        "tables": ["family_bind"],
        "frs": ["FR-FAMILY-001", "FR-FAMILY-002", "FR-FAMILY-003", "FR-FAMILY-004",
                "FR-FAMILY-005", "FR-FAMILY-007", "FR-FAMILY-009", "FR-FAMILY-011"],
        "features": [
            ("提交绑定申请", "家属按老人手机号发起申请，校验手机号存在性（不存在返回 2002）", "FR-FAMILY-001"),
            ("重复申请拦截", "同一对家属—老人已存在 PENDING / APPROVED 时返回 4001", "FR-FAMILY-001"),
            ("绑定上限控制", "老人已绑定家属数达上限（默认 5，入 sys_config 的 family_bind_max）返回 4002", "FR-FAMILY-001"),
            ("确认 / 拒绝", "老人端或管理员端确认；代确认时写入操作人 approved_by 与原因 approve_note 留痕", "FR-FAMILY-001"),
            ("权限生效控制", "未确认（PENDING）不产生任何数据访问权限，确认后家属才可见档案、指标、预警", "FR-FAMILY-005 / 011"),
            ("解绑", "任一方发起即时生效，状态置 REVOKED，历史处理记录保留用于追溯", "FR-FAMILY-003"),
            ("代管多老人", "一个家属可绑定多位老人，提供已生效老人列表供切换", "FR-FAMILY-002"),
            ("代录与代咨询", "绑定生效后家属可代老人录入指标、发起 AI 咨询", "FR-FAMILY-004 / 009"),
        ],
        "classes": [
            ("FamilyRouter", "接口层：申请 / 待确认列表 / 确认 / 解绑 / 代管列表", "#eff6ff", "#3b82f6"),
            ("FamilyBindService", "应用层：状态机流转、上限与重复校验", "#eff6ff", "#3b82f6"),
            ("BindStateMachine", "PENDING → APPROVED / REJECTED；APPROVED → REVOKED", "#fef3c7", "#d97706"),
            ("FamilyRepository", "数据层：family_bind 读写与状态查询", "#f8fafc", "#64748b"),
            ("FamilyBindModel", "实体：family_bind 表映射（含确认留痕字段）", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("FamilyRouter", "FamilyBindService", "调用"),
            ("FamilyBindService", "BindStateMachine", "流转"),
            ("FamilyBindService", "FamilyRepository", "读写"),
            ("FamilyRepository", "FamilyBindModel", "映射"),
        ],
        "structure": {
            "iface": ["FamilyRouter\\napp/api/v1/family.py"],
            "service": ["FamilyBindService\\n上限校验 · 重复申请拦截", "BindStateMachine\\n四态流转 + 幂等"],
            "data": ["FamilyRepository\\nfamily_bind 读写"],
            "side": ["sys_config\\nfamily_bind_max 默认 5", "→ 决定 M2/M3/M5 可见范围"],
        },
    },
    {
        "code": "M7",
        "cn": "护工端",
        "en": "CARE",
        "duty": "负责老人列表（异常优先）、老人详情、处理记录，责任范围强制隔离",
        "chapter": "契约第 8 章",
        "tables": ["care_relation", "health_record", "health_warning"],
        "frs": ["FR-CARE-001", "FR-CARE-002", "FR-CARE-003", "FR-CARE-004",
                "FR-CARE-005", "FR-CARE-006", "FR-CARE-007", "FR-CARE-009", "FR-CARE-010"],
        "features": [
            ("负责老人列表", "按 care_relation 返回在管老人，一屏看到最新血压、血糖、睡眠与待处理预警数", "FR-CARE-001"),
            ("状态分色标识", "老人状态按 正常 NORMAL / 关注 WATCH / 异常 ABNORMAL 标识", "FR-CARE-002"),
            ("异常优先排序", "高风险老人置顶，便于护工优先处理", "FR-CARE-010"),
            ("老人详情", "档案 + 最近指标 + 预警三合一视图", "FR-CARE-003 / 004"),
            ("处理预警", "登记处理结果，复用 M5 的处理闭环并写入留痕", "FR-CARE-005"),
            ("处理记录", "查看本人历史处理记录，供交接与追溯", "FR-CARE-006"),
            ("责任范围隔离", "护工仅可见分配给自己的老人，隔离在后端强制实现", "FR-CARE-007"),
            ("老人筛选", "按状态或时段筛选负责老人", "FR-CARE-009"),
        ],
        "classes": [
            ("CareRouter", "接口层：负责老人列表 / 老人详情 / 处理记录", "#eff6ff", "#3b82f6"),
            ("CareService", "应用层：状态聚合排序、详情组装", "#eff6ff", "#3b82f6"),
            ("CareScopeResolver", "按 care_relation 计算护工负责范围", "#fef3c7", "#d97706"),
            ("CareRepository", "数据层：care_relation 与跨表聚合查询", "#f8fafc", "#64748b"),
            ("ElderStatusAssembler", "聚合最近指标与待处理预警，产出 NORMAL / WATCH / ABNORMAL", "#f0fdf4", "#16a34a"),
        ],
        "class_edges": [
            ("CareRouter", "CareService", "调用"),
            ("CareService", "CareScopeResolver", "取范围"),
            ("CareService", "ElderStatusAssembler", "组装状态"),
            ("CareService", "CareRepository", "查询"),
        ],
        "structure": {
            "iface": ["CareRouter\\napp/api/v1/care.py"],
            "service": ["CareService\\n详情组装 · 排序", "ElderStatusAssembler\\n正常/关注/异常"],
            "data": ["care_relation 分配关系", "health_record 最近指标", "health_warning 待处理预警"],
            "side": ["复用 M5 处理闭环\\n写入处理留痕", "责任范围强制隔离\\n（P5 铁律）"],
        },
    },
    {
        "code": "M8",
        "cn": "后台管理",
        "en": "ADMIN",
        "duty": "用户管理、创建护工/管理员、阈值与指标配置、知识库维护、统计",
        "chapter": "契约第 9 章",
        "tables": ["user", "sys_config", "knowledge_document"],
        "frs": ["FR-ADMIN-001", "FR-ADMIN-002", "FR-ADMIN-004", "FR-ADMIN-005",
                "FR-ADMIN-006", "FR-ADMIN-009", "FR-ADMIN-010",
                "FR-REPORT-001", "FR-REPORT-002", "FR-REPORT-003"],
        "features": [
            ("用户管理", "按角色与关键词查询用户；禁用后该用户不可登录（token 立即失效）", "FR-ADMIN-001 / 002"),
            ("创建护工 / 管理员", "仅管理员可建号，role 仅允许 CARE / ADMIN；密码 bcrypt 存储不回显（D-01）", "FR-ADMIN-001"),
            ("阈值配置", "配置各指标四档阈值区间，保存后即时生效，无需重启", "FR-ADMIN-004 / 009"),
            ("配置入表", "阈值与系统参数全部存 sys_config，禁止写死在代码里（铁律 2）", "FR-ADMIN-010"),
            ("健康指标配置", "配置可录入的指标类型、单位与正常范围", "FR-ADMIN-005"),
            ("知识库维护", "知识条目增删改；上传文档自动解析建索引为【选配】本期不实现", "FR-ADMIN-006"),
            ("统计概览", "用户数、咨询数、预警数按周期统计，口径与明细一致", "FR-REPORT-001~003"),
        ],
        "classes": [
            ("AdminRouter", "接口层：用户 / 阈值 / 指标 / 知识库 / 统计", "#eff6ff", "#3b82f6"),
            ("UserAdminService", "建号、启停用、角色约束", "#eff6ff", "#3b82f6"),
            ("ThresholdConfigService", "阈值读写并刷新缓存，保证即时生效", "#fef3c7", "#d97706"),
            ("KnowledgeService", "知识条目维护与索引重建", "#f0fdf4", "#16a34a"),
            ("StatisticsService", "按周期聚合用户 / 咨询 / 预警指标", "#f0fdf4", "#16a34a"),
            ("AdminGuard", "管理员权限依赖，非 ADMIN 一律 1002", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("AdminRouter", "AdminGuard", "鉴权"),
            ("AdminRouter", "UserAdminService", "调用"),
            ("AdminRouter", "ThresholdConfigService", "调用"),
            ("AdminRouter", "KnowledgeService", "调用"),
            ("AdminRouter", "StatisticsService", "调用"),
        ],
        "structure": {
            "iface": ["AdminRouter\\napp/api/v1/admin.py", "AdminGuard\\n仅 ADMIN 可访问"],
            "service": ["UserAdminService", "ThresholdConfigService\\n写后刷缓存", "KnowledgeService", "StatisticsService"],
            "data": ["user 账号", "sys_config 阈值与参数", "knowledge_document 知识条目"],
            "side": ["写 sys_config 后\\nM5 即时生效（FR-ADMIN-009）"],
        },
    },
    {
        "code": "M9",
        "cn": "系统配置",
        "en": "CONFIG",
        "duty": "向前端下发指标类型与生效阈值，保证前端不写死正常范围",
        "chapter": "契约第 10 章",
        "tables": ["sys_config"],
        "frs": ["FR-ADMIN-004", "FR-ADMIN-010", "FR-HEALTH-012"],
        "features": [
            ("指标类型下发", "返回可录入的指标类型、单位与取值范围，供前端表单渲染", "FR-ADMIN-005"),
            ("生效阈值下发", "返回当前生效的四档阈值，供前端展示正常范围与高亮判断", "FR-ADMIN-004"),
            ("前端零硬编码", "正常范围一律取自本模块接口，前端不得写死（铁律 2）", "FR-ADMIN-010"),
            ("配置读取加速", "阈值读取走进程内缓存，管理端写入后立即失效重建", "FR-HEALTH-012"),
        ],
        "classes": [
            ("ConfigRouter", "接口层：指标类型 / 生效阈值", "#eff6ff", "#3b82f6"),
            ("SysConfigService", "应用层：配置读取、分组过滤、缓存失效", "#eff6ff", "#3b82f6"),
            ("ThresholdCache", "进程内阈值缓存，写入后即时失效", "#f0fdf4", "#16a34a"),
            ("SysConfigRepository", "数据层：sys_config 读写", "#f8fafc", "#64748b"),
            ("SysConfigModel", "实体：sys_config 表映射（key / value / type / group）", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("ConfigRouter", "SysConfigService", "调用"),
            ("SysConfigService", "ThresholdCache", "读缓存"),
            ("SysConfigService", "SysConfigRepository", "读库"),
            ("SysConfigRepository", "SysConfigModel", "映射"),
        ],
        "structure": {
            "iface": ["ConfigRouter\\napp/api/v1/config.py"],
            "service": ["SysConfigService\\n分组读取 · 缓存失效", "ThresholdCache\\n进程内缓存"],
            "data": ["SysConfigRepository\\nsys_config 读写"],
            "side": ["M3 异常判定\\nM5 阈值规则\\n共用同一份阈值"],
        },
    },
]

# 前端端别（系统结构图第二层，不计入 §3 四件套）
CLIENTS = [
    ("老人端", "13 个界面"),
    ("家属端", "5 个界面"),
    ("护工端", "6 个界面"),
    ("管理员端", "10 个界面"),
    ("公共 / 认证", "4 个界面"),
]

# 技术模块（被各业务模块共用的基础设施，指导老师 2026-09-15 语音要求区分「业务/技术」两类）
# T1 / T2 / T4 出四件套（B 档），T3 / T5 / T6 仅列清单
TECH_MODULES = [
    {
        "code": "T1",
        "cn": "数据访问与事务管理",
        "en": "TECH · DATA ACCESS",
        "duty": "统一数据库会话与连接池、事务边界、Repository 基类与通用查询",
        "shared_by": "全部 9 个业务模块",
        "chapter": "技术模块（B 档出四件套）",
        "tables": ["全部 15 张表"],
        "frs": ["技术支撑，无独立 FR"],
        "features": [
            ("会话管理", "按请求创建与释放 SQLAlchemy Session，请求结束自动归还连接池，杜绝连接泄漏", "技术支撑"),
            ("事务边界", "Service 层用 `with uow:` 显式提交或回滚，禁止在接口层直接写库", "技术支撑"),
            ("Repository 基类", "封装通用增删改查、分页查询与软删除过滤，各业务模块的 Repository 继承它", "技术支撑"),
            ("连接池配置", "池大小、获取超时、回收时间由 `.env` 下发，不写死在代码", "技术支撑"),
            ("只读查询优化", "趋势与统计类查询走只读会话，不开启写事务", "技术支撑"),
            ("一致性兜底", "外键约束 + 应用层唯一性校验（如家属重复申请、绑定上限）双层保障", "技术支撑"),
        ],
        "classes": [
            ("SessionFactory", "创建与回收会话，持有连接池配置", "#f0fdf4", "#16a34a"),
            ("UnitOfWork", "事务上下文：进入开事务、退出提交或回滚", "#f0fdf4", "#16a34a"),
            ("BaseRepository", "通用 CRUD / 分页 / 软删除过滤的抽象基类", "#f8fafc", "#64748b"),
            ("ProfileRepository", "档案访问（继承 BaseRepository）", "#f8fafc", "#64748b"),
            ("HealthRecordRepository", "指标访问（继承 BaseRepository）", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("UnitOfWork", "SessionFactory", "取会话"),
            ("ProfileRepository", "BaseRepository", "泛化"),
            ("HealthRecordRepository", "BaseRepository", "泛化"),
            ("BaseRepository", "SessionFactory", "使用"),
        ],
        "structure": {
            "iface": ["无对外 HTTP 端点\\n技术模块，被业务模块在服务层调用"],
            "service": ["UnitOfWork\\n事务边界 · 提交 / 回滚"],
            "data": ["SessionFactory\\n连接池 · 会话生命周期", "BaseRepository\\n通用 CRUD / 分页 / 软删除"],
            "side": [".env\\nDB_URL · 池大小 · 超时", "MySQL 8.0\\n15 张表"],
        },
        "public_funcs": [
            ("get_session()", "获取当前请求的数据库会话（依赖注入）"),
            ("unit_of_work()", "开启事务上下文，退出时提交或回滚"),
            ("BaseRepository.page()", "通用分页查询，支持过滤与排序"),
            ("BaseRepository.get_by_id()", "按主键取实体，自动过滤软删除记录"),
            ("BaseRepository.save()", "新增或更新实体并刷新审计字段"),
        ],
    },
    {
        "code": "T2",
        "cn": "鉴权与请求上下文",
        "en": "TECH · AUTH CONTEXT",
        "duty": "JWT 签发与校验、当前用户注入、角色校验、密码学工具与请求级上下文",
        "shared_by": "除注册、登录外的全部接口",
        "chapter": "技术模块（B 档出四件套）",
        "tables": ["user（读取账号与状态）"],
        "frs": ["FR-AUTH-003", "FR-AUTH-004", "FR-AUTH-005", "FR-AUTH-012"],
        "features": [
            ("JWT 签发与校验", "HMAC 签名，过期或失效返回 1001，前端跳登录页", "FR-AUTH-003"),
            ("当前用户注入", "以 `Depends(get_current_user)` 提供当前用户，替代 Java 方案的 ThreadLocal 上下文", "FR-AUTH-003"),
            ("角色校验", "`require_role(...)` 依赖声明允许的角色，越权访问返回 1002", "FR-AUTH-004 / 005"),
            ("账号状态校验", "禁用账号的 Token 立即失效，配合后台的启用 / 禁用", "FR-AUTH-012"),
            ("密码学工具", "bcrypt 哈希与校验，全系统禁止明文与 MD5", "FR-AUTH-012"),
            ("请求级上下文", "生成请求 ID、记录客户端 IP 与当前用户，供日志模块使用", "技术支撑"),
        ],
        "classes": [
            ("PasswordHasher", "bcrypt 哈希与校验", "#f0fdf4", "#16a34a"),
            ("JwtProvider", "JWT 签发、解析与失效列表维护", "#f0fdf4", "#16a34a"),
            ("CurrentUser", "当前用户数据结构（用户 ID / 角色 / 状态）", "#f8fafc", "#64748b"),
            ("RequireRole", "角色校验依赖工厂，按角色放行或返回 1002", "#fef3c7", "#d97706"),
            ("RequestContext", "请求级上下文：请求 ID / IP / 用户，供日志与审计使用", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("RequireRole", "JwtProvider", "取用户"),
            ("RequireRole", "CurrentUser", "产出"),
            ("JwtProvider", "PasswordHasher", "同层工具"),
            ("RequestContext", "CurrentUser", "引用"),
        ],
        "structure": {
            "iface": ["Depends(get_current_user)\\n被除注册 / 登录外的全部接口引用", "require_role(...)\\n后台与配置类接口"],
            "service": ["JwtProvider\\n签发 / 解析 / 失效列表", "PasswordHasher\\nbcrypt", "RequestContext\\n请求 ID · IP · 用户"],
            "data": ["user 表\\n读取账号与状态"],
            "side": [".env\\nJWT_SECRET · JWT_TTL", "被 T4 日志模块引用\\n（写入操作人）"],
        },
        "public_funcs": [
            ("get_current_user()", "解析请求头 token，返回当前用户（依赖注入）"),
            ("require_role(*roles)", "角色校验依赖工厂，角色不符返回 1002"),
            ("create_token(user)", "签发 JWT，返回 token 与有效期"),
            ("hash_password(raw)", "bcrypt 哈希，禁明文与 MD5"),
            ("verify_password(raw, hashed)", "bcrypt 校验，失败累计次数由 sys_config 控制"),
        ],
    },
    {
        "code": "T3",
        "cn": "统一响应与异常处理",
        "en": "TECH · RESPONSE",
        "duty": "统一响应封装 `ApiResponse[T]`、错误码体系、全局异常处理器",
        "shared_by": "全部接口",
        "chapter": "技术模块（B 档仅列清单）",
        "tables": ["—"],
        "frs": ["技术支撑，无独立 FR"],
    },
    {
        "code": "T4",
        "cn": "日志与审计",
        "en": "TECH · LOGGING",
        "duty": "请求日志、异常日志、AI 调用留痕与关键操作审计",
        "shared_by": "全部模块；AI 调用与预警处理留痕",
        "chapter": "技术模块（B 档出四件套）",
        "tables": ["ai_log"],
        "frs": ["FR-ADMIN-008"],
        "features": [
            ("请求日志", "记录方法、路径、耗时、状态码与操作人，由中间件统一完成", "FR-ADMIN-008"),
            ("异常日志", "全局异常处理器记录堆栈并统一返回 5001，不向客户端泄露内部信息", "FR-ADMIN-008"),
            ("AI 调用留痕", "模型标识、输入输出 token 数、耗时、成功与否写入 `ai_log`", "技术支撑"),
            ("关键操作审计", "登录、阈值修改、账号启停用等关键动作留痕，可追溯到人", "FR-ADMIN-008"),
            ("日志分级", "DEBUG / INFO / WARNING / ERROR 四级，生产默认 INFO", "技术支撑"),
            ("与主流程解耦", "日志写入失败不影响业务返回，避免日志成为故障放大器", "技术支撑"),
        ],
        "classes": [
            ("RequestLogMiddleware", "请求进出拦截，记录耗时与状态码", "#f0fdf4", "#16a34a"),
            ("ExceptionHandler", "全局异常处理，统一转 5001 并记堆栈", "#fef2f2", "#ef4444"),
            ("AuditLogger", "关键操作审计留痕（登录 / 阈值 / 启停用）", "#fef3c7", "#d97706"),
            ("AiCallLogger", "AI 调用明细写入 ai_log 表", "#fef3c7", "#d97706"),
            ("LoggingConfig", "日志级别、格式与输出目标配置", "#f8fafc", "#64748b"),
        ],
        "class_edges": [
            ("RequestLogMiddleware", "AuditLogger", "写审计"),
            ("ExceptionHandler", "AuditLogger", "记异常"),
            ("AiCallLogger", "AuditLogger", "同族"),
            ("LoggingConfig", "RequestLogMiddleware", "配置"),
        ],
        "structure": {
            "iface": ["RequestLogMiddleware\\n请求日志中间件", "ExceptionHandler\\n全局异常处理器"],
            "service": ["AuditLogger\\n关键操作审计", "AiCallLogger\\nAI 调用留痕"],
            "data": ["ai_log 表", "文件日志\\n按天滚动"],
            "side": ["core/config\\n日志级别（.env）", "被 M4 / M5 / M8 调用"],
        },
        "public_funcs": [
            ("request_id()", "取当前请求 ID，用于串联一次请求的全部日志"),
            ("write_audit_log(user, action, payload)", "写关键操作审计日志，失败不影响业务"),
            ("log_ai_call(agent, model, tokens, latency, success)", "写 AI 调用明细到 ai_log 表"),
            ("to_api_error(exc)", "把内部异常统一转成 5001 与对外提示文案"),
        ],
    },
    {
        "code": "T5",
        "cn": "配置与阈值缓存",
        "en": "TECH · CONFIG CACHE",
        "duty": "`.env` 与 `sys_config` 的读取、进程内阈值缓存与写后失效",
        "shared_by": "M3 指标判定、M5 预警规则、M9 配置下发",
        "chapter": "技术模块（B 档仅列清单）",
        "tables": ["sys_config"],
        "frs": ["FR-ADMIN-010"],
    },
    {
        "code": "T6",
        "cn": "文件存储",
        "en": "TECH · STORAGE",
        "duty": "文件上传与访问的存储抽象（本地 / OSS）",
        "shared_by": "M4 知识库、头像（本期不做）",
        "chapter": "技术模块（B 档仅列清单）【选配】",
        "tables": ["knowledge_document"],
        "frs": ["FR-KB-005"],
    },
]

# 模块 ↔ 目录 / 文件 对应（回应老师"一般按文件分模块"的工程惯例）
MODULE_FILES = [
    ("M1", "认证与权限", "`app/api/v1/auth.py`",
     "`app/services/auth_service.py`", "`app/core/security.py`（T2 提供）"),
    ("M2", "健康档案", "`app/api/v1/profiles.py`",
     "`app/services/profile_service.py`", "`app/repositories/profile_repo.py`"),
    ("M3", "健康指标", "`app/api/v1/health.py`",
     "`app/services/health_service.py`", "`app/repositories/health_repo.py`"),
    ("M4", "AI 咨询与智能体编排", "`app/api/v1/ai.py`",
     "`app/services/chat_service.py`", "`app/agent/`（agent / orchestrator / retriever / llm）"),
    ("M5", "主动预警", "`app/api/v1/alerts.py`、`notifications.py`",
     "`app/services/alert_service.py`", "`app/repositories/alert_repo.py`"),
    ("M6", "家属绑定", "`app/api/v1/family.py`",
     "`app/services/family_service.py`", "`app/repositories/family_repo.py`"),
    ("M7", "护工端", "`app/api/v1/care.py`",
     "`app/services/care_service.py`", "`app/repositories/care_repo.py`"),
    ("M8", "后台管理", "`app/api/v1/admin.py`",
     "`app/services/admin_service.py`", "`app/repositories/admin_repo.py`"),
    ("M9", "系统配置", "`app/api/v1/config.py`",
     "`app/services/config_service.py`", "`app/repositories/config_repo.py`"),
    ("T1", "数据访问与事务管理", "（无 HTTP 端点）",
     "`app/repositories/base.py`", "`app/core/database.py`（会话与连接池）"),
    ("T2", "鉴权与请求上下文", "（无 HTTP 端点）",
     "`app/core/deps.py`", "`app/core/security.py`"),
    ("T3", "统一响应与异常处理", "（无 HTTP 端点）",
     "`app/core/exceptions.py`", "`app/schemas/common.py`（`ApiResponse[T]`）"),
    ("T4", "日志与审计", "（中间件与全局处理器）",
     "`app/core/logging.py`", "`app/repositories/ai_log_repo.py`"),
    ("T5", "配置与阈值缓存", "（无 HTTP 端点）",
     "`app/core/config.py`", "`app/core/cache.py`"),
    ("T6", "文件存储【选配】", "（无 HTTP 端点）",
     "`app/core/storage.py`", "本地 / OSS 适配器"),
]

# 支撑层
INFRA = [
    ("MySQL 8.0", "InnoDB · utf8mb4\\n15 张表"),
    ("LLM 服务", "DeepSeek / 通义千问 / GLM-4\\n三选一，改 .env 即换"),
    ("向量库", "Chroma / FAISS\\nRAG 检索"),
    ("文件存储", "本地 / OSS\\n知识库文档"),
]
