# -*- coding: utf-8 -*-
"""03.概要设计 v2.0 生成器 · 接口函数数据（全量 45 个）
单一来源：§3.x.3 模块接口说明表 与 §5.2 模块间接口函数设计，均由本文件生成。
字段：m 所属模块 / name 函数名 / file 文件名 / api 方法与路径 / summary 功能概要
     params 参数表 (类型, 变量名, I/O, 说明) / ret 返回值 (类型, 说明)
     detail 详细说明 / note 使用注意事项
"""

FUNCS = [
    # ---------------- M1 AUTH（4） ----------------
    dict(m="M1", name="register", file="app/api/v1/auth.py", api="POST /api/auth/register",
         summary="用户注册",
         params=[("RegisterIn", "payload", "IN", "手机号 / 密码 / 姓名 / 角色")],
         ret=("ApiResponse[UserOut]", "data 为新用户基本信息；角色越界返回 4003"),
         detail="校验手机号格式与唯一性，密码经 bcrypt 哈希后落库，返回新用户摘要信息。",
         note="role 仅接受 ELDER / FAMILY；传入 CARE / ADMIN 直接返回 4003，不做静默降级（D-01）。"),
    dict(m="M1", name="login", file="app/api/v1/auth.py", api="POST /api/auth/login",
         summary="用户登录",
         params=[("LoginIn", "payload", "IN", "手机号 + 密码"),
                 ("UserRepository", "repo", "IN", "用户查询依赖（注入）")],
         ret=("ApiResponse[LoginOut]", "data 含 token、expires_in 与用户信息"),
         detail="按手机号取用户，bcrypt 校验密码，通过后签发 JWT 并更新最近登录时间。",
         note="账号被禁用返回 1003；密码错误累计次数超限由 sys_config 控制并记录。"),
    dict(m="M1", name="logout", file="app/api/v1/auth.py", api="POST /api/auth/logout",
         summary="退出登录",
         params=[("str", "token", "IN", "当前请求携带的 token")],
         ret=("ApiResponse[None]", "data 为 null，code 0 表示登出成功"),
         detail="将当前 token 写入失效列表，后续携带该 token 的请求返回 1001。",
         note="幂等：重复登出仍返回成功，不报错。"),
    dict(m="M1", name="get_me", file="app/api/v1/auth.py", api="GET /api/auth/me",
         summary="获取当前用户信息",
         params=[("CurrentUser", "user", "IN", "由鉴权依赖注入的当前登录用户")],
         ret=("ApiResponse[UserOut]", "data 为当前用户基本信息与角色"),
         detail="从 token 解析出的用户上下文中读取资料，供前端刷新页面时恢复登录态。",
         note="前端不得据此自行判断角色含义，跳转目标页以后端返回的 role 为准。"),

    # ---------------- M2 PROFILE（5） ----------------
    dict(m="M2", name="list_profiles", file="app/api/v1/profiles.py", api="GET /api/profiles",
         summary="档案列表（按角色隔离）",
         params=[("CurrentUser", "user", "IN", "当前登录用户，决定可见范围")],
         ret=("ApiResponse[list[ProfileOut]]", "当前用户有权查看的档案集合"),
         detail="由 ScopeResolver 计算可见集合：老人本人 / 家属已绑定 / 护工负责 / 管理员全部。",
         note="数据隔离在后端强制实现，前端不传过滤参数，传了也不生效（P5 原则）。"),
    dict(m="M2", name="create_profile", file="app/api/v1/profiles.py", api="POST /api/profiles",
         summary="创建档案",
         params=[("ProfileIn", "payload", "IN", "姓名 / 性别 / 出生日期 / 身高体重 / 病史 / 慢病标签"),
                 ("CurrentUser", "user", "IN", "档案归属账号")],
         ret=("ApiResponse[ProfileOut]", "新建档案的完整信息"),
         detail="校验必填项与取值范围，慢病标签序列化为 JSON 数组存储，档案归属当前用户。",
         note="一位账号可建多份档案（本人 / 代管老人），供后续多档案切换。"),
    dict(m="M2", name="get_profile", file="app/api/v1/profiles.py", api="GET /api/profiles/{id}",
         summary="档案详情",
         params=[("int", "profile_id", "IN", "档案 ID（路径参数）")],
         ret=("ApiResponse[ProfileOut]", "档案完整字段"),
         detail="按 ID 读取档案，先做可见性校验再返回，已软删除的档案返回 2002。",
         note="越权访问他人档案返回 1002，不得泄露记录是否存在之外的信息。"),
    dict(m="M2", name="update_profile", file="app/api/v1/profiles.py", api="PUT /api/profiles/{id}",
         summary="更新档案",
         params=[("int", "profile_id", "IN", "档案 ID"),
                 ("ProfileUpdate", "payload", "IN", "同创建的字段集合，允许部分更新")],
         ret=("ApiResponse[ProfileOut]", "更新后的档案信息"),
         detail="先校验可见性与可写权限，再按字段更新并刷新更新时间。",
         note="慢病标签整体覆盖式更新，前端需提交完整标签数组。"),
    dict(m="M2", name="delete_profile", file="app/api/v1/profiles.py", api="DELETE /api/profiles/{id}",
         summary="删除档案（软删除）",
         params=[("int", "profile_id", "IN", "档案 ID")],
         ret=("ApiResponse[None]", "code 0 表示删除成功"),
         detail="将 deleted 置 1 而非物理删除，关联指标与预警记录保留以便追溯。",
         note="前端须二次确认；软删除后档案不出现在任何列表与统计中。"),

    # ---------------- M3 HEALTH（4） ----------------
    dict(m="M3", name="create_record", file="app/api/v1/health.py", api="POST /api/health/records",
         summary="录入健康指标并同步检测异常",
         params=[("RecordIn", "payload", "IN", "档案 ID / 指标类型 / 数值 / 测量时间 / 备注"),
                 ("CurrentUser", "user", "IN", "录入人（本人 / 家属代录 / 护工）")],
         ret=("ApiResponse[RecordOut]", "data 含 record_id、is_abnormal、risk_level、warning_id"),
         detail="校验类型与取值范围后落库，随即同步调用阈值检测；命中异常时联动 M5 生成预警并返回 warning_id。",
         note="五类指标的 values 结构不同（血压需 systolic / diastolic），由 Pydantic 判别联合类型校验。"),
    dict(m="M3", name="list_records", file="app/api/v1/health.py", api="GET /api/health/records",
         summary="指标历史列表",
         params=[("int", "profile_id", "IN", "档案 ID"),
                 ("str", "type", "IN", "指标类型，可空表示全部"),
                 ("int", "page / page_size", "IN", "分页参数，默认 1 / 20")],
         ret=("ApiResponse[PageResult[RecordOut]]", "list / total / page / page_size"),
         detail="按档案与类型过滤，按测量时间倒序分页返回。",
         note="查询前先做档案可见性校验，避免越权读取他人指标。"),
    dict(m="M3", name="delete_record", file="app/api/v1/health.py", api="DELETE /api/health/records/{id}",
         summary="删除指标记录",
         params=[("int", "record_id", "IN", "记录 ID")],
         ret=("ApiResponse[None]", "code 0 表示删除成功"),
         detail="物理删除该条指标记录；已由该记录触发的预警不被删除，保留历史。",
         note="仅录入人、档案归属人或管理员可删除，其余返回 1002。"),
    dict(m="M3", name="get_trend", file="app/api/v1/health.py", api="GET /api/health/trend",
         summary="指标趋势数据（供 ECharts）",
         params=[("int", "profile_id", "IN", "档案 ID"),
                 ("str", "type", "IN", "指标类型"),
                 ("int", "days", "IN", "统计天数，默认 30")],
         ret=("ApiResponse[TrendOut]", "dates / series / normal_range / abnormal_points"),
         detail="按天聚合指标值，normal_range 取自 sys_config，abnormal_points 标注超阈值点及等级。",
         note="正常范围必须由后端下发，前端禁止写死（铁律 2）。"),

    # ---------------- M4 AI（4） ----------------
    dict(m="M4", name="chat", file="app/api/v1/ai.py", api="POST /api/ai/chat",
         summary="发起健康咨询（多 Agent 编排）",
         params=[("ChatIn", "payload", "IN", "档案 ID / 问题 / session_id（可空）"),
                 ("CurrentUser", "user", "IN", "提问人（老人本人或家属代问）")],
         ret=("ApiResponse[ChatOut]", "answer / intent / agent / safety_level / sources / warning_id / disclaimer"),
         detail="会话不存在则新建；组装档案摘要与近 7 天指标 → 意图识别 → 选择 Agent 执行 → RAG 检索注入 → 调模型生成 → 落库并返回，异常意图联动生成预警。",
         note="模型不可用返回 3001 但不得阻断录入与预警主流程（D-04）；单次限字数、按用户限频，超限返回 3002。"),
    dict(m="M4", name="list_sessions", file="app/api/v1/ai.py", api="GET /api/ai/sessions",
         summary="会话列表",
         params=[("int", "profile_id", "IN", "档案 ID，可空表示本人全部会话")],
         ret=("ApiResponse[list[SessionOut]]", "会话 ID、标题与最后消息时间"),
         detail="按档案与当前用户过滤会话，按更新时间倒序返回。",
         note="家属仅可见自己发起的会话，不可见老人与其他家属的咨询记录。"),
    dict(m="M4", name="list_messages", file="app/api/v1/ai.py", api="GET /api/ai/sessions/{id}/messages",
         summary="会话内消息列表",
         params=[("int", "session_id", "IN", "会话 ID")],
         ret=("ApiResponse[list[MessageOut]]", "消息内容及 intent / agent / sources 等元信息"),
         detail="按时间正序返回会话内全部问答，供前端恢复上下文展示。",
         note="前端需展示 intent 与 agent 字段，这是多 Agent 编排的直观体现。"),
    dict(m="M4", name="delete_session", file="app/api/v1/ai.py", api="DELETE /api/ai/sessions/{id}",
         summary="删除会话",
         params=[("int", "session_id", "IN", "会话 ID")],
         ret=("ApiResponse[None]", "code 0 表示删除成功"),
         detail="级联删除会话下的消息记录，已触发的预警不受影响。",
         note="仅会话发起人可删除，管理员不可代删。"),

    # ---------------- M5 ALERT（8） ----------------
    dict(m="M5", name="list_alerts", file="app/api/v1/alerts.py", api="GET /api/alerts",
         summary="预警列表（含每人已读状态）",
         params=[("str", "status / level", "IN", "处理状态与风险等级筛选，均可空"),
                 ("int", "page / page_size", "IN", "分页参数")],
         ret=("ApiResponse[PageResult[AlertOut]]", "含 ai_summary、summary_status、my_read_status、trigger_source"),
         detail="按当前用户可见范围查询预警，外联 alert_receiver 取当前用户已读状态，统计口径与详情一致。",
         note="ai_summary 可为 null，前端须显示“摘要生成中 / 失败可查看原始数据”，不得隐藏整条预警（D-04）。"),
    dict(m="M5", name="get_alert", file="app/api/v1/alerts.py", api="GET /api/alerts/{id}",
         summary="预警详情",
         params=[("int", "warning_id", "IN", "预警 ID")],
         ret=("ApiResponse[AlertDetailOut]", "列表字段 + history_trend + handles"),
         detail="返回指标值、阈值、近 7 天趋势与全部处理记录；访问详情时把当前用户的接收记录置为已读。",
         note="置已读只影响当前用户那条 alert_receiver，不得改动他人状态（D-05）。"),
    dict(m="M5", name="handle_alert", file="app/api/v1/alerts.py", api="POST /api/alerts/{id}/handle",
         summary="提交处理结果（闭环）",
         params=[("int", "warning_id", "IN", "预警 ID"),
                 ("HandleIn", "payload", "IN", "处理方式 action + 说明 result")],
         ret=("ApiResponse[AlertOut]", "更新后的预警信息"),
         detail="写入 warning_handle_record（处理人 / 方式 / 说明 / 时间），并将处理状态置为 RESOLVED。",
         note="处理后其余接收人界面显示“已由 XXX 于 XX 时间处理”；已处理不等于已读（D-05）。"),
    dict(m="M5", name="update_alert_status", file="app/api/v1/alerts.py", api="PUT /api/alerts/{id}/status",
         summary="更新中间态（处理中 / 已忽略）",
         params=[("int", "warning_id", "IN", "预警 ID"),
                 ("StatusIn", "payload", "IN", "status，取值 PROCESSING 或 IGNORED")],
         ret=("ApiResponse[AlertOut]", "更新后的预警信息"),
         detail="用于护工已接单但尚未完成的中间态流转，仅允许在合法状态之间迁移。",
         note="不允许把 RESOLVED 回退为 PROCESSING；非法迁移返回 2001。"),
    dict(m="M5", name="mark_alert_read", file="app/api/v1/alerts.py", api="POST /api/alerts/{id}/read",
         summary="标记已读（仅当前用户）",
         params=[("int", "warning_id", "IN", "预警 ID"),
                 ("CurrentUser", "user", "IN", "当前登录用户")],
         ret=("ApiResponse[None]", "code 0 表示标记成功"),
         detail="仅更新当前用户在 alert_receiver 中的 read_status 与阅读时间。",
         note="不影响其他接收人，也不改变预警的处理状态；重复调用幂等。"),
    dict(m="M5", name="retry_summary", file="app/api/v1/alerts.py", api="POST /api/alerts/{id}/summary/retry",
         summary="AI 摘要重试（D-04）",
         params=[("int", "warning_id", "IN", "预警 ID")],
         ret=("ApiResponse[AlertOut]", "重试后的摘要与 summary_status"),
         detail="仅在 summary_status 为 FAILED 时允许手动触发，重新异步生成个性化摘要。",
         note="模型仍不可用返回 3001，预警本身保持可见可用，不影响主流程。"),
    dict(m="M5", name="alert_statistics", file="app/api/v1/alerts.py", api="GET /api/alerts/statistics",
         summary="预警统计",
         params=[("CurrentUser", "user", "IN", "当前用户，决定 unread 口径")],
         ret=("ApiResponse[AlertStatsOut]", "pending / high_risk / today_new / handled / unread"),
         detail="聚合待处理、高风险、今日新增、已处理与未读五项指标。",
         note="pending 为全局未处理条数，unread 为当前用户未读条数，两者口径不同（D-05）。"),
    dict(m="M5", name="unread_count", file="app/api/v1/notifications.py", api="GET /api/notifications/unread",
         summary="通知未读数（前端红点）",
         params=[("CurrentUser", "user", "IN", "当前登录用户")],
         ret=("ApiResponse[UnreadOut]", "unread 未读条数与 latest_level 最高等级"),
         detail="读取当前用户未读接收记录数量与其中最高风险等级，数据量极小。",
         note="前端以 30 秒周期轮询；本期通知范围仅站内，无短信与电话外呼（D-03）。"),

    # ---------------- M6 FAMILY（5） ----------------
    dict(m="M6", name="create_bind", file="app/api/v1/family.py", api="POST /api/family/bind",
         summary="提交绑定申请",
         params=[("BindIn", "payload", "IN", "老人手机号 / 亲属关系 / 申请备注"),
                 ("CurrentUser", "user", "IN", "申请人家属账号")],
         ret=("ApiResponse[BindOut]", "申请单信息，status 为 PENDING"),
         detail="按手机号定位老人档案，校验是否存在、是否重复申请、是否超出绑定上限，通过后写入 PENDING 申请单。",
         note="老人不存在返回 2002；重复申请返回 4001；超出上限（sys_config 的 family_bind_max，默认 5）返回 4002。"),
    dict(m="M6", name="list_bind_requests", file="app/api/v1/family.py", api="GET /api/family/bind-requests",
         summary="待我确认的绑定申请",
         params=[("CurrentUser", "user", "IN", "老人本人或管理员")],
         ret=("ApiResponse[list[BindRequestOut]]", "待确认申请列表，含申请人姓名与关系"),
         detail="返回指向当前用户名下档案的 PENDING 申请，供老人或管理员确认。",
         note="申请单中的老人手机号需脱敏展示（138****8000）。"),
    dict(m="M6", name="confirm_bind", file="app/api/v1/family.py", api="PUT /api/family/bind/{id}/confirm",
         summary="确认或拒绝绑定申请",
         params=[("int", "bind_id", "IN", "申请单 ID"),
                 ("ConfirmIn", "payload", "IN", "action（APPROVE / REJECT）+ note")],
         ret=("ApiResponse[BindOut]", "更新后的绑定记录"),
         detail="确认置 APPROVED 并写确认时间；拒绝置 REJECTED。代确认时记录操作人与代确认原因。",
         note="确认后家属才获得数据访问权限，PENDING 期间无任何权限（D-02）。"),
    dict(m="M6", name="list_bound_elders", file="app/api/v1/family.py", api="GET /api/family/elders",
         summary="已生效的代管老人列表",
         params=[("CurrentUser", "user", "IN", "家属账号")],
         ret=("ApiResponse[list[ElderBriefOut]]", "APPROVED 状态的代管老人摘要"),
         detail="返回该家属绑定生效的老人，供前端档案切换器使用。",
         note="仅 APPROVED 状态可见；REVOKED 后该老人立即从列表消失。"),
    dict(m="M6", name="unbind", file="app/api/v1/family.py", api="DELETE /api/family/bind/{id}",
         summary="解绑",
         params=[("int", "bind_id", "IN", "绑定记录 ID"),
                 ("CurrentUser", "user", "IN", "发起方（家属或老人）")],
         ret=("ApiResponse[None]", "code 0 表示解绑成功"),
         detail="状态置为 REVOKED 而非物理删除，数据访问权限即时收回。",
         note="任一方发起即时生效；历史处理记录保留用于追溯（FR-FAMILY-003）。"),

    # ---------------- M7 CARE（3） ----------------
    dict(m="M7", name="list_care_elders", file="app/api/v1/care.py", api="GET /api/care/elders",
         summary="负责老人列表（异常优先）",
         params=[("str", "status", "IN", "状态筛选：NORMAL / WATCH / ABNORMAL，可空"),
                 ("CurrentUser", "user", "IN", "护工账号")],
         ret=("ApiResponse[list[CareElderOut]]", "含最新血压、血糖、睡眠与待处理预警数"),
         detail="按 care_relation 取在管老人，聚合最近指标与待处理预警数，异常者置顶排序。",
         note="护工仅可见分配给自己的老人，隔离在后端强制实现（P5 原则）。"),
    dict(m="M7", name="get_care_elder", file="app/api/v1/care.py", api="GET /api/care/elders/{profile_id}",
         summary="老人详情（档案 + 指标 + 预警）",
         params=[("int", "profile_id", "IN", "老人档案 ID")],
         ret=("ApiResponse[CareElderDetailOut]", "档案、最近指标列表与预警列表"),
         detail="三合一视图组装，一次请求满足护工照护场景，减少前端串行请求。",
         note="非本人负责的老人返回 1002，不得以“不存在”掩盖越权。"),
    dict(m="M7", name="list_handles", file="app/api/v1/care.py", api="GET /api/care/handles",
         summary="本人处理记录",
         params=[("CurrentUser", "user", "IN", "护工账号"),
                 ("int", "page / page_size", "IN", "分页参数")],
         ret=("ApiResponse[PageResult[HandleRecordOut]]", "历史上报的处理记录"),
         detail="按处理人过滤 warning_handle_record，按时间倒序返回，供交接与追溯。",
         note="只返回本人处理记录，管理员查全部请走后台管理模块。"),

    # ---------------- M8 ADMIN（10） ----------------
    dict(m="M8", name="list_users", file="app/api/v1/admin.py", api="GET /api/admin/users",
         summary="用户列表",
         params=[("str", "role / keyword", "IN", "角色与关键字筛选，均可空"),
                 ("int", "page / page_size", "IN", "分页参数")],
         ret=("ApiResponse[PageResult[UserOut]]", "用户列表，密码字段不回显"),
         detail="按角色与姓名 / 手机号关键字查询用户。",
         note="仅 ADMIN 可访问，其余角色返回 1002。"),
    dict(m="M8", name="create_user", file="app/api/v1/admin.py", api="POST /api/admin/users",
         summary="创建护工 / 管理员账号（D-01）",
         params=[("AdminUserIn", "payload", "IN", "手机号 / 初始密码 / 姓名 / 角色")],
         ret=("ApiResponse[UserOut]", "新建账号基本信息"),
         detail="校验手机号唯一与角色合法性，密码 bcrypt 哈希后落库，不回显密码。",
         note="role 仅允许 CARE 或 ADMIN；传 ELDER / FAMILY 返回 2001（这两类走公开注册）。"),
    dict(m="M8", name="set_user_status", file="app/api/v1/admin.py", api="PUT /api/admin/users/{id}/status",
         summary="禁用 / 启用用户",
         params=[("int", "user_id", "IN", "用户 ID"),
                 ("StatusIn", "payload", "IN", "enabled 布尔值")],
         ret=("ApiResponse[UserOut]", "更新后的用户信息"),
         detail="更新 status 字段；禁用后该用户已签发的 token 立即失效。",
         note="不允许禁用自己，避免管理员自锁；不允许禁用最后一个管理员。"),
    dict(m="M8", name="list_thresholds", file="app/api/v1/admin.py", api="GET /api/admin/thresholds",
         summary="阈值配置列表",
         params=[("str", "indicator", "IN", "指标标识筛选，可空")],
         ret=("ApiResponse[list[ThresholdOut]]", "各指标四档阈值区间与启用状态"),
         detail="读取 sys_config 中 group_name 为 threshold 的配置，转为结构化阈值对象。",
         note="阈值存储在 sys_config，禁止在代码中写死（铁律 2）。"),
    dict(m="M8", name="update_threshold", file="app/api/v1/admin.py", api="PUT /api/admin/thresholds/{id}",
         summary="更新阈值（即时生效）",
         params=[("int", "config_id", "IN", "配置 ID"),
                 ("ThresholdIn", "payload", "IN", "四档区间与启用状态")],
         ret=("ApiResponse[ThresholdOut]", "更新后的阈值配置"),
         detail="写库后立即失效进程内阈值缓存，下一次指标录入与预警判定即采用新阈值。",
         note="需校验区间不重叠且连续覆盖，避免出现判定空档（FR-ADMIN-009）。"),
    dict(m="M8", name="list_indicators", file="app/api/v1/admin.py", api="GET /api/admin/indicators",
         summary="健康指标配置",
         params=[("CurrentUser", "user", "IN", "管理员账号")],
         ret=("ApiResponse[list[IndicatorOut]]", "指标类型、单位与取值范围"),
         detail="返回可录入指标的类型定义，供管理端维护与前端表单渲染。",
         note="指标类型为受控枚举，前端不得自行扩展取值。"),
    dict(m="M8", name="list_knowledge", file="app/api/v1/admin.py", api="GET /api/admin/knowledge",
         summary="知识库条目列表",
         params=[("str", "category / keyword", "IN", "分类与关键字筛选，均可空")],
         ret=("ApiResponse[PageResult[KnowledgeOut]]", "知识条目列表"),
         detail="分页查询知识文档，支持按分类（高血压 / 糖尿病 / 睡眠等）过滤。",
         note="知识内容增删改仅管理员可操作，其他角色只读（FR-KB-006）。"),
    dict(m="M8", name="create_knowledge", file="app/api/v1/admin.py", api="POST /api/admin/knowledge",
         summary="新增知识条目",
         params=[("KnowledgeIn", "payload", "IN", "标题 / 分类 / 正文")],
         ret=("ApiResponse[KnowledgeOut]", "新建知识条目"),
         detail="写入知识文档并触发向量化重建，供 RAG 检索使用。",
         note="索引重建异步执行，失败不影响条目本身可查询。"),
    dict(m="M8", name="upload_knowledge", file="app/api/v1/admin.py", api="POST /api/admin/knowledge/upload",
         summary="上传文档自动解析建索引【选配·本期不实现】",
         params=[("UploadFile", "file", "IN", "健康资料文档（PDF / Word / 文本）")],
         ret=("ApiResponse[KnowledgeOut]", "解析结果摘要（本期不实现，接口占位）"),
         detail="上传文档后自动解析、切分、向量化并写入索引；本期仅保留接口定义与文档说明。",
         note="【选配】功能，本期不实现（FR-KB-005 / E-03），评审时按“声明不做”口径说明。"),
    dict(m="M8", name="get_statistics", file="app/api/v1/admin.py", api="GET /api/admin/statistics",
         summary="统计概览",
         params=[("str", "range", "IN", "统计周期：7d / 30d / all"),
                 ("CurrentUser", "user", "IN", "管理员账号")],
         ret=("ApiResponse[StatisticsOut]", "用户数、咨询数、预警数等聚合指标"),
         detail="按周期聚合用户、咨询与预警三类指标，口径与各模块明细一致。",
         note="报表数据须与明细口径一致（FR-REPORT-006），差异需在文档中说明过滤条件。"),

    # ---------------- M9 CONFIG（2） ----------------
    dict(m="M9", name="list_config_indicators", file="app/api/v1/config.py", api="GET /api/config/indicators",
         summary="可录入指标类型下发",
         params=[("CurrentUser", "user", "IN", "登录用户")],
         ret=("ApiResponse[list[IndicatorOut]]", "指标类型、单位与取值范围"),
         detail="从 sys_config 读取启用的指标定义，供前端录入表单动态渲染。",
         note="前端表单选项一律来自本接口，不得写死指标列表。"),
    dict(m="M9", name="list_effective_thresholds", file="app/api/v1/config.py", api="GET /api/config/thresholds",
         summary="当前生效阈值下发",
         params=[("CurrentUser", "user", "IN", "登录用户"),
                 ("str", "indicator", "IN", "指标标识筛选，可空")],
         ret=("ApiResponse[list[ThresholdOut]]", "四档阈值区间，供前端展示正常范围"),
         detail="读取阈值缓存或数据库，返回当前生效区间，用于趋势图正常范围与异常高亮。",
         note="前端展示正常范围必须调本接口，写死范围会导致改阈值后显示不一致（铁律 2）。"),
]

# ---------------------------------------------------------------- 接口性质
# 按指导老师 2026-09-15 语音口径：接口分「外部接口」（提供给其他模块 / 文件调用）与
# 「内部接口」（文件或类内部使用、不对外公开）。下列为需要特别标注的少数函数，
# 其余默认按「对外接口（HTTP，供前端调用）」处理。
NATURE_DEFAULT = "对外接口（HTTP，供前端调用）"
NATURE_OVERRIDE = {
    ("M1", "get_me"): "对外接口（HTTP）；同时供 T2 鉴权依赖在每次请求中复用",
    ("M2", "list_profiles"): "对外接口（HTTP）；其可见范围计算被 M3 / M5 / M7 复用",
    ("M3", "create_record"): "对外接口（HTTP）；内部同步触发 M5 生成预警",
    ("M5", "get_alert"): "对外接口（HTTP）；M7 护工端详情复用同一查询",
    ("M5", "handle_alert"): "对外接口（HTTP）；M7 护工端复用，保证处理闭环口径唯一",
    ("M8", "update_threshold"): "对外接口（HTTP）；写后即时失效 M3 / M5 共用的阈值缓存",
    ("M9", "list_effective_thresholds"): "对外接口（HTTP）；后端 M3 / M5 读同一份阈值缓存",
}

# ---------------------------------------------------------------- 模块间内部调用接口
# 指导老师要求区分「外部接口 / 内部接口」：本节列出**被其他模块在进程内调用的函数**，
# 按老师口径属于"对外提供的接口"（相对调用方模块而言）；各模块内部私有方法属"内部接口"，
# 不逐个列出，只在各业务模块类图中以 `_` 前缀方法体现。
INTERNAL_FUNCS = [
    dict(m="M2", name="resolve_visible_profiles", file="app/services/profile_service.py",
         api="模块间调用（进程内）", caller="M3 指标录入 / M5 预警生成 / M7 护工端",
         summary="解析当前用户的可见档案集合",
         params=[("CurrentUser", "user", "IN", "当前登录用户"),
                 ("enum", "scene", "IN", "使用场景：LIST / WRITE / STAT")],
         ret=("list[int]", "可见的 profile_id 列表；无可见档案时返回空列表"),
         detail="按角色分流：老人取本人档案、家属取 APPROVED 绑定、护工取 care_relation 在管、管理员取全部。",
         note="**禁止在接口层重复实现**，否则数据隔离会出现口径不一致（P5 原则）；读写场景参数不同，写场景会额外校验档案未软删除。"),
    dict(m="M5", name="create_warning_from_record", file="app/services/alert_service.py",
         api="模块间调用（进程内）", caller="M3 录入流程 / M4 RiskAgent",
         summary="由指标记录生成预警",
         params=[("HealthRecord", "record", "IN", "已落库的指标记录"),
                 ("enum", "source", "IN", "触发来源：DATA_INPUT / AI_CHAT")],
         ret=("Warning | None", "命中阈值返回预警实体；未命中返回 None"),
         detail="读 sys_config 阈值判级 → 落 health_warning → 写 alert_receiver 接收人 → 投递异步摘要任务。",
         note="**同步执行且不等待 AI 摘要**（D-04）；模型不可用时预警仍正常生成，这是主闭环的兜底设计。"),
    dict(m="M5", name="judge_risk_level", file="app/services/rule_engine.py",
         api="模块间调用（进程内）", caller="M5 内部 / M3 录入前预判",
         summary="阈值规则判定",
         params=[("str", "indicator", "IN", "指标标识，如 BLOOD_PRESSURE_SYSTOLIC"),
                 ("Decimal", "val1", "IN", "主值（收缩压 / 血糖 / 心率 / 睡眠时长 / 步数）"),
                 ("Decimal", "val2", "IN", "次值（舒张压 / 睡眠质量），可空"),
                 ("list[str]", "chronic_tags", "IN", "档案慢病标签，用于个体微调")],
         ret=("tuple[int, str]", "(风险等级 0~3, 展示值文本)"),
         detail="从阈值缓存读取四档区间，按区间命中判级；慢病标签可对临界值上调一档。",
         note="阈值一律来自 sys_config，**代码中不得出现硬编码数值**（铁律 2）；区间不连续视为配置错误并记日志。"),
    dict(m="M4", name="generate_summary", file="app/services/summary_worker.py",
         api="模块间调用（异步任务）", caller="M5 预警生成后投递 / M5 摘要重试接口",
         summary="异步生成预警摘要",
         params=[("int", "warning_id", "IN", "预警 ID"),
                 ("bool", "retry", "IN", "是否为人工重试")],
         ret=("str", "summary_status 取值：SUCCESS / FAILED / SKIPPED"),
         detail="组装该档案近 7 天趋势与本条指标 → 调 LlmClient 生成个性化说明 → 写回 ai_summary 与 summary_status。",
         note="**不阻塞预警生成主流程**（D-04）；模型不可用时置 FAILED，由重试接口再触发，预警本身保持可见可用。"),
    dict(m="M4", name="orchestrate_chat", file="app/agent/orchestrator.py",
         api="模块间调用（进程内）", caller="M4 咨询接口 / M5 摘要复用同一 LlmClient",
         summary="多 Agent 编排执行",
         params=[("CurrentUser", "user", "IN", "提问人"),
                 ("int", "profile_id", "IN", "针对的档案"),
                 ("str", "question", "IN", "用户问题")],
         ret=("ChatResult", "含 answer / intent / agent / safety_level / sources / warning_id"),
         detail="意图识别 → 选择 Agent（Health / HealthData / Risk / Emergency）→ RAG 检索注入 → 调模型 → 安全分级 → 落库并返回。",
         note="异常意图会回调 M5 的 `create_warning_from_record`；模型调用超时阈值 8 秒，超时降级为固定就医提示。"),
    dict(m="M7", name="assemble_elder_status", file="app/services/care_service.py",
         api="模块间调用（进程内）", caller="M7 负责老人列表接口",
         summary="聚合老人状态供工作台展示",
         params=[("list[int]", "profile_ids", "IN", "护工负责的档案集合"),
                 ("int", "days", "IN", "回溯天数，默认 7")],
         ret=("list[ElderStatusOut]", "含最新指标、待处理预警数与状态枚举"),
         detail="跨 health_record 与 health_warning 聚合，按异常优先排序，产出 NORMAL / WATCH / ABNORMAL。",
         note="入参必须是 M2 `resolve_visible_profiles` 的结果，**禁止自行拼 SQL 取全量老人**（P5 原则）。"),
    dict(m="M9", name="get_effective_threshold", file="app/core/cache.py",
         api="模块间调用（进程内）", caller="M3 异常判定 / M5 判级 / M9 下发前端",
         summary="读取生效阈值（带进程内缓存）",
         params=[("str", "indicator", "IN", "指标标识，可空表示全部")],
         ret=("Threshold | list[Threshold]", "四档区间对象；标识不存在时抛配置异常"),
         detail="优先读进程内缓存，未命中回源 sys_config 并写回缓存。",
         note="三处**共用同一份缓存**；后台改阈值后必须立即失效，否则判定与展示不一致（FR-ADMIN-009）。"),
    dict(m="T4", name="write_audit_log", file="app/core/logging.py",
         api="模块间调用（进程内）", caller="M1 登录 / M8 阈值与账号操作 / M5 处理预警",
         summary="写审计日志",
         params=[("CurrentUser", "user", "IN", "操作人，可空表示系统动作"),
                 ("str", "action", "IN", "动作标识，如 THRESHOLD_UPDATE"),
                 ("dict", "payload", "IN", "动作上下文，敏感字段须脱敏")],
         ret=("None", "无返回值；写入失败仅记本地日志"),
         detail="把关键操作写入审计目标（文件 / 可选入库），携带请求 ID 便于串联一次请求的全部日志。",
         note="**日志写入失败不得影响业务返回**；密码、Token 等敏感字段禁止写入。"),
]

