<template><div class="ky-page" v-loading="loading"><div class="ky-page-header"><h2 class="ky-page-title">【选配】健康日报 / 周报</h2></div><div class="ky-card"><el-space wrap><el-select v-model="id" placeholder="选择已绑定老人"><el-option v-for="e in elders" :key="e.profile_id" :label="e.profile.name" :value="e.profile_id" /></el-select><el-radio-group v-model="days"><el-radio-button :label="1">近 24 小时</el-radio-button><el-radio-button :label="7">近 7 天</el-radio-button></el-radio-group><el-button type="primary" :disabled="!id" @click="load">汇总实际记录</el-button></el-space><p class="ky-sub">按测量时间筛选实际录入记录，仅统计有记录的指标。该报告为统计汇总。</p><el-alert v-if="error" type="error" :title="error" :closable="false" /></div><div v-if="generated" class="ky-card"><div class="ky-card__title">周期：{{ fmtDate(start) }} ～ {{ fmtDate(end) }}</div><el-table :data="summaries"><el-table-column prop="name" label="指标" /><el-table-column prop="count" label="记录数" /><el-table-column prop="abnormal" label="异常记录数" /><el-table-column prop="latest" label="本周期最近值" /><el-table-column prop="time" label="最近测量时间" min-width="160" /></el-table><p class="ky-sub">未记录的指标无法评价健康状态；异常判定取自每条记录的后台检测结果。未生成模型建议。</p></div></div></template>
<script setup>
import {ref,onMounted} from 'vue'
import {listElders,listRecords} from '@/api'
import {TYPES,NAME,recordText,fmtDate} from '@/utils/format'
const elders=ref([]),id=ref(null),days=ref(1),summaries=ref([]),generated=ref(false),loading=ref(false),error=ref(''),start=ref(''),end=ref('')
async function allRecords(type){const rows=[];let page=1;while(true){const d=await listRecords({profile_id:id.value,type,page,page_size:100});rows.push(...d.list);if(rows.length>=d.total||!d.list.length)return rows;page++}}
async function load(){loading.value=true;error.value='';generated.value=false;try{const finish=new Date(),begin=new Date(finish.getTime()-days.value*86400000);start.value=begin.toISOString();end.value=finish.toISOString();summaries.value=await Promise.all(TYPES.map(async type=>{const rows=(await allRecords(type)).filter(r=>{const t=new Date(r.measured_at.replace(' ','T'));return t>=begin&&t<=finish});return{name:NAME[type],count:rows.length,abnormal:rows.filter(r=>r.is_abnormal).length,latest:rows.length?recordText(rows[0]):'未记录',time:rows.length?rows[0].measured_at:'—'}}));generated.value=true}catch(e){error.value=e.message}finally{loading.value=false}}
onMounted(async()=>{try{elders.value=await listElders();id.value=elders.value[0]?.profile_id}catch(e){error.value=e.message}})
</script>
