process.chdir(__dirname);
const { chromium }=require('playwright'),fs=require('fs');const base='http://127.0.0.1:5174';const suffix=String(Date.now()).slice(-8),testPhone='139'+suffix,testName='UI新增护工'+suffix;
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],consoleIssues=[],results=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))consoleIssues.push({type:m.type(),text:m.text()})});
 await page.goto(base+'/login');await page.getByPlaceholder('请输入 11 位手机号').fill('13000000001');await page.getByPlaceholder('请输入密码').fill('Abc123456');await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL('**/admin/**');
 await page.goto(base+'/admin/users');await page.getByRole('button',{name:'创建护工 / 管理员账号',exact:true}).click();
 let dialog=page.getByRole('dialog');let inputs=dialog.locator('input');await inputs.nth(1).fill(testName);await inputs.nth(2).fill(testPhone);await inputs.nth(3).fill('Abc123456');
 let response=page.waitForResponse(r=>r.url().endsWith('/admin/users')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'创建账号',exact:true}).click();let d=await(await response).json();if(d.code!==0)throw Error('Create user failed '+JSON.stringify(d));await page.getByText(testName,{exact:true}).waitFor();results.push({admin_create_user:true});
 const row=page.locator('tr').filter({hasText:testName});
 await row.getByRole('button',{name:'禁用',exact:true}).click();await page.getByRole('button',{name:'确定',exact:true}).click();await row.getByRole('button',{name:'启用',exact:true}).waitFor();results.push({admin_disable:true});
 await row.getByRole('button',{name:'启用',exact:true}).click();await page.getByRole('button',{name:'确定',exact:true}).click();await row.getByRole('button',{name:'禁用',exact:true}).waitFor();results.push({admin_enable:true});
 await row.getByRole('button',{name:'改为管理员',exact:true}).click();await page.getByRole('button',{name:'确定',exact:true}).click();await row.getByRole('button',{name:'改为护工',exact:true}).waitFor();results.push({admin_role_change:true});
 await page.goto(base+'/admin/knowledge');await page.getByRole('button',{name:'新增条目',exact:true}).click();dialog=page.getByRole('dialog');inputs=dialog.locator('input');await inputs.nth(0).fill('UI测试健康文章');await dialog.locator('.el-select').click();await page.getByRole('option',{name:'安全提示',exact:true}).click();await dialog.locator('textarea').fill('仅用于浏览器联调的知识条目：健康建议不构成医疗诊断。发现持续异常请联系医疗人员。');response=page.waitForResponse(r=>r.url().endsWith('/admin/knowledge')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'保存条目',exact:true}).click();d=await(await response).json();if(d.code!==0)throw Error('Knowledge create failed '+JSON.stringify(d));await page.getByText('UI测试健康文章',{exact:true}).waitFor();results.push({knowledge_create:true});
 let article=page.locator('tr').filter({hasText:'UI测试健康文章'});await article.getByRole('button',{name:'编辑',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('textarea').fill('知识编辑联调结果：引用真实来源并标记适用范围，健康建议不构成医疗诊断。');response=page.waitForResponse(r=>r.url().includes('/admin/knowledge/')&&r.request().method()==='PUT');await dialog.getByRole('button',{name:'保存条目',exact:true}).click();d=await(await response).json();if(d.code!==0)throw Error('Knowledge edit failed');results.push({knowledge_edit:true});
 await page.getByRole('button',{name:'重建向量索引',exact:true}).click();await page.getByText('索引重建完成',{exact:true}).waitFor();results.push({knowledge_reindex:true});
 await article.getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'确定',exact:true}).click();await page.getByText('条目已删除',{exact:true}).waitFor();results.push({knowledge_delete:true});
 await page.goto(base+'/admin/thresholds');await page.getByRole('button',{name:'修改',exact:true}).first().click();dialog=page.getByRole('dialog');const original=await dialog.locator('input').nth(0).inputValue();await dialog.locator('input').nth(0).fill('invalid');response=page.waitForResponse(r=>r.url().includes('/admin/thresholds/')&&r.request().method()==='PUT');await dialog.getByRole('button',{name:'保存到后台',exact:true}).click();d=await(await response).json();if(d.code!==2001)throw Error('Invalid threshold should fail');await page.getByText(/阈值表达式无效/).first().waitFor();results.push({threshold_invalid_rejected:true});await dialog.locator('input').nth(0).fill(original);response=page.waitForResponse(r=>r.url().includes('/admin/thresholds/')&&r.request().method()==='PUT');await dialog.getByRole('button',{name:'保存到后台',exact:true}).click();d=await(await response).json();if(d.code!==0)throw Error('Threshold save failed');results.push({threshold_save:true});
 await page.goto(base+'/admin/indicators');await page.getByRole('button',{name:'修改配置',exact:true}).first().click();dialog=page.getByRole('dialog');response=page.waitForResponse(r=>r.url().includes('/admin/indicators/')&&r.request().method()==='PUT');await dialog.getByRole('button',{name:'保存配置',exact:true}).click();d=await(await response).json();if(d.code!==0)throw Error('Indicator save failed');results.push({indicator_config_save:true});
 await page.goto(base+'/admin/statistics');await page.waitForLoadState('networkidle');await page.screenshot({path:'admin-statistics.png',fullPage:true});
 // Request failure is injected only in this test, with no application mock fallback.
 await page.route('**/api/admin/users**',r=>r.abort('failed'));await page.goto(base+'/admin/users');await page.getByText('无法连接服务器，请确认后端服务已启动',{exact:true}).first().waitFor();await page.screenshot({path:'network-failure.png',fullPage:true});results.push({network_failure_visible:true});
 if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync('mutation-results.json',JSON.stringify({database:'isolated SQLite',real_model:false,results,page_errors:errors,console:consoleIssues},null,2));console.log(JSON.stringify({passed:results.length,page_errors:errors.length,console_issues:consoleIssues.length}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
